[main]
# The default PPD profile
default=power-saver
battery_detection=true

[profiles]
# PPD = TuneD
power-saver=qwreey-powersave
balanced=qwreey-balanced
performance=qwreey-performance

[battery]
# PPD = TuneD
performance=qwreey-battery-performance

