[main]
# The default PPD profile
default=power-saver
battery_detection=true

[profiles]
# PPD = TuneD
power-saver=qwreey-plugged-powersave
balanced=qwreey-plugged-balanced
performance=qwreey-plugged-performance

[battery]
# PPD = TuneD
power-saver=qwreey-battery-powersave
balanced=qwreey-battery-balanced
performance=qwreey-battery-performance
