[ids]
*

[global]
overload_tap_timeout = 260

[main]
capslock = overload(control, hangeul)
leftcontrol = leftalt
leftalt = layer(altmod)

[altmod]
u = home
o = end
i = up
j = left
k = down
l = right
y = pageup
h = pagedown
tab = swapm(alttab, tab)
grave = swapm(alttab, grave)
esc = swapm(alttab, esc)
1 = f1
2 = f2
3 = f3
4 = f4
5 = f5
6 = f6
7 = f7
8 = f8
9 = f9
0 = f10
minus = f11
equal = f12
leftbrace = volumedown
rightbrace = volumeup
backslash = mute
p = pause
dot = brightnessup
comma = brightnessdown

[alttab:A]
tab = A-tab
i = A-up
j = A-left
k = A-down
l = A-right
grave = A-grave
esc = A-esc

